# Generated by Django 4.2.5 on 2023-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ourserviceimage/')),
                ('title', models.CharField(max_length=255, verbose_name='Service name')),
                ('text', models.CharField(max_length=255, verbose_name='Service text')),
                ('css', models.CharField(default='-', max_length=255, null=True, verbose_name='Service css')),
            ],
            options={
                'verbose_name': 'Service slide',
                'verbose_name_plural': 'Service slides',
            },
        ),
    ]
