# Generated by Django 4.2.5 on 2023-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200, verbose_name='Title name')),
                ('news_text', models.CharField(max_length=200, verbose_name='News text')),
                ('news_css', models.CharField(default='-', max_length=200, null=True, verbose_name='CSS class')),
            ],
            options={
                'verbose_name': 'News slide',
                'verbose_name_plural': 'News slides',
            },
        ),
    ]
