# Generated by Django 4.2.5 on 2023-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Small Name')),
                ('description', models.CharField(max_length=255, verbose_name='Title news card')),
            ],
            options={
                'verbose_name': 'News card',
                'verbose_name_plural': 'News cards',
            },
        ),
    ]
