# Generated by Django 4.2.5 on 2023-11-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latestnews', '0002_newscard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCard',
        ),
    ]
