# Generated by Django 4.2.5 on 2023-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestnews', '0003_delete_newscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsslider',
            name='news_image',
            field=models.ImageField(null=True, upload_to='cliderimg/'),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='news_css',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='CSS class'),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='news_text',
            field=models.CharField(max_length=255, verbose_name='News text'),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='news_title',
            field=models.CharField(max_length=100, verbose_name='Title name'),
        ),
    ]
