# Generated by Django 4.2.5 on 2023-11-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latestnews', '0006_alter_newsslider_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsslider',
            name='news_image',
        ),
    ]
