# Generated by Django 4.2.5 on 2023-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=255, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=255, verbose_name='Phone:'),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='StatusName',
            field=models.CharField(max_length=255, verbose_name='Status name'),
        ),
    ]
