# Generated by Django 4.2.5 on 2023-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_order_name_alter_order_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email:'),
        ),
    ]
