# Generated by Django 4.2.5 on 2023-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='testimonialsimage/')),
                ('title', models.CharField(max_length=255, verbose_name='Testimonial title')),
                ('text', models.CharField(max_length=255, verbose_name='Testimonial text')),
                ('css', models.CharField(default='', max_length=255, null=True, verbose_name='Testimonial css')),
            ],
            options={
                'verbose_name': 'Testimonial slide',
                'verbose_name_plural': 'Testimonial sliders',
            },
        ),
    ]
