# Generated by Django 4.2.5 on 2023-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsslider',
            name='img',
            field=models.ImageField(upload_to='testimonialsimage/'),
        ),
    ]
