# Generated by Django 4.2.5 on 2023-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonialsslider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsslider',
            name='css',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='Testimonial css'),
        ),
    ]
