# Generated by Django 4.2.5 on 2023-12-16 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonialsslider_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsslider',
            name='img',
            field=models.ImageField(upload_to='testimonialsimage/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'pdf', 'doc', 'svg'])]),
        ),
    ]
